#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for utils/time
#
# IDENTIFICATION
#    src/backend/utils/time/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/utils/time
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	backend_runtime_time.o \
	combocid.o \
	snapmgr.o

include $(top_srcdir)/src/backend/common.mk
