CREATE EXTENSION test_backend_runtime;

SELECT test_backend_exit_runtime_continuation();
SELECT test_backend_dsm_shutdown_is_backend_local();
SELECT test_backend_interrupt_wakes_target_latch();
SELECT test_backend_thread_create_join();
SELECT test_backend_thread_exit_join();
SELECT test_backend_thread_runtime_state();
SELECT test_backend_thread_split_initializers();
SELECT test_carrier_threaded_guc_lock_depth_is_carrier_local();
SELECT test_carrier_attach_detach_current_work();
SELECT test_carrier_protocol_park_prepare_commit();
SELECT test_protocol_scheduler_poll_buffered_read();
SELECT test_protocol_read_wake_applies_backend_interrupt();
SELECT test_carrier_misc_state_is_carrier_local();
SELECT test_thread_install_adopts_backend_fallback_state();
SELECT test_thread_install_adopts_session_execution_fallback_state();
SELECT test_thread_install_adopts_connection_fallback_state();
SELECT test_backend_pgproc_has_logical_id();
SELECT test_backend_thread_ids_are_logical();
SELECT test_session_loop_state_is_session_local();
SELECT test_session_tcop_state_is_session_local();
SELECT test_session_xact_callback_state_is_session_local();
SELECT test_session_backup_state_is_session_local();
SELECT test_session_database_state_is_session_local();
SELECT test_session_tablespace_state_is_session_local();
SELECT test_session_binary_upgrade_state_is_session_local();
SELECT test_session_datetime_state_is_session_local();
SELECT test_session_text_search_state_is_session_local();
SELECT test_session_prepared_statement_state_is_session_local();
SELECT test_session_invalidation_callback_state_is_session_local();
SELECT test_session_ri_globals_state_is_session_local();
SELECT test_session_relmap_state_is_session_local();
SELECT test_session_reset_closed_state();
SELECT test_session_on_commit_state_is_session_local();
SELECT test_session_sequence_state_is_session_local();
SELECT test_session_large_object_state_is_session_local();
SELECT test_session_regex_portal_state_is_session_local();
SELECT test_session_async_state_is_session_local();
SELECT test_session_encoding_state_is_session_local();
SELECT test_session_temp_file_state_is_session_local();
SELECT test_session_random_state_is_session_local();
SELECT test_session_optimizer_state_is_session_local();
SELECT test_session_plan_cache_state_is_session_local();
SELECT test_session_namespace_state_is_session_local();
SELECT test_session_locale_state_is_session_local();
SELECT test_session_catalog_lookup_state_is_session_local();
SELECT test_session_extension_module_state_is_session_local();
SELECT test_runtime_server_guc_state_is_runtime_local();
SELECT test_runtime_extension_module_state_is_runtime_local();
SELECT test_session_guc_rebind_table_matches_registry();
SELECT test_session_connection_guc_state_is_session_local();
SELECT test_session_parser_state_is_session_local();
SELECT test_session_vacuum_state_is_session_local();
SELECT test_session_buffer_io_state_is_session_local();
SELECT test_session_xact_defaults_are_session_local();
SELECT test_session_lock_wait_state_is_session_local();
SELECT test_session_logging_state_is_session_local();
SELECT test_session_pgstat_state_is_session_local();
SELECT test_session_query_id_state_is_session_local();
SELECT test_session_storage_guc_state_is_session_local();
SELECT test_session_user_guc_state_is_session_local();
SELECT test_session_user_identity_state_is_session_local();
SELECT test_session_command_guc_state_is_session_local();
SELECT test_session_replication_guc_state_is_session_local();
SELECT test_session_general_guc_state_is_session_local();
SELECT test_session_compat_guc_state_is_session_local();
SELECT test_session_access_wal_guc_state_is_session_local();
SELECT test_session_jit_guc_state_is_session_local();
SELECT test_session_jit_provider_state_is_session_local();
SELECT test_session_misc_guc_state_is_session_local();
SELECT test_session_guc_state_is_session_local();
SELECT test_session_sort_guc_state_is_session_local();
SELECT test_session_query_memory_state_is_session_local();
SELECT test_session_planner_cost_state_is_session_local();
SELECT test_session_planner_method_state_is_session_local();
SELECT test_backend_interrupt_holdoffs_are_backend_local();
SELECT test_backend_pending_interrupts_are_backend_local();
SELECT test_backend_exit_state_is_backend_local();
SELECT test_backend_pgstat_pending_state_is_backend_local();
SELECT test_backend_activity_state_is_backend_local();
SELECT test_backend_memory_manager_state_is_backend_local();
SELECT test_backend_utility_state_is_backend_local();
SELECT test_backend_reset_closed_state();
SELECT test_backend_parallel_state_is_backend_local();
SELECT test_backend_instrumentation_state_is_backend_local();
SELECT test_runtime_hot_bucket_cache_tracks_current_work();
SELECT test_backend_buffer_state_is_backend_local();
SELECT test_backend_storage_state_is_backend_local();
SELECT test_backend_lock_state_is_backend_local();
SELECT test_backend_wait_state_is_backend_local();
SELECT test_backend_wait_completion_publication();
SELECT test_backend_wait_completion_publication_policy();
SELECT test_backend_ipc_state_is_backend_local();
SELECT test_backend_transaction_state_is_backend_local();
SELECT test_backend_timeout_state_is_backend_local();
SELECT test_backend_walsender_state_is_backend_local();
SELECT test_backend_replication_state_is_backend_local();
SELECT test_backend_logical_replication_state_is_backend_local();
SELECT test_backend_xlog_state_is_backend_local();
SELECT test_backend_recovery_state_is_backend_local();
SELECT test_backend_maintenance_worker_state_is_backend_local();
SELECT test_backend_autovacuum_state_is_backend_local();
SELECT test_backend_repack_state_is_backend_local();
SELECT test_backend_aio_state_is_backend_local();
SELECT test_backend_extension_module_state_is_backend_local();
SELECT test_pmchild_thread_backend_signal_api();
SELECT test_pmchild_thread_backend_reset_api();
SELECT test_pmchild_pooled_logical_backend_signal_api();
SELECT test_pmchild_thread_backend_publication_race();
SELECT test_backend_core_state_is_backend_local();
SELECT test_backend_command_log_state_is_backend_local();
SELECT test_backend_expr_interp_state_is_backend_local();
SELECT test_execution_debug_query_string_is_execution_local();
SELECT test_execution_error_state_is_execution_local();
SELECT test_execution_memory_contexts_are_execution_local();
SELECT test_execution_spi_state_is_execution_local();
SELECT test_execution_active_portal_is_execution_local();
SELECT test_execution_reset_closed_state();
CREATE EVENT TRIGGER test_backend_runtime_ddl_command_end
	ON ddl_command_end
	EXECUTE FUNCTION test_backend_runtime_noop_event_trigger();
SELECT test_execution_event_trigger_query_state_reset();
DROP EVENT TRIGGER test_backend_runtime_ddl_command_end;
SELECT test_execution_vacuum_state_is_execution_local();
SELECT test_execution_node_io_state_is_execution_local();
SELECT test_execution_basebackup_state_is_execution_local();
SELECT test_execution_analyze_state_is_execution_local();
SELECT test_execution_extension_state_is_execution_local();
SELECT test_execution_matview_state_is_execution_local();
SELECT test_execution_snapshot_combo_state_is_execution_local();
SELECT test_execution_xloginsert_state_is_execution_local();
SELECT test_execution_xact_state_is_execution_local();
SELECT test_execution_transaction_cleanup_state_is_execution_local();
SELECT test_execution_reporting_replication_state_is_execution_local();
SELECT test_execution_guc_error_state_is_execution_local();
SELECT test_execution_catalog_state_is_execution_local();
SELECT test_execution_catalog_cache_state_is_execution_local();
SELECT test_execution_relmap_state_is_execution_local();
SELECT test_execution_inval_twophase_state_is_execution_local();
SELECT test_execution_async_state_is_execution_local();
SELECT test_execution_misc_scratch_state_is_execution_local();
SELECT test_execution_resource_owners_are_execution_local();
SELECT test_connection_socket_io_is_connection_local();
SELECT test_connection_protocol_state_is_connection_local();
SELECT test_connection_protocol_byte_probe();
SELECT test_connection_reset_closed_state();
SELECT test_connection_warning_state_is_connection_local();
SELECT test_connection_output_state_is_connection_local();
SELECT test_connection_identity_state_is_connection_local();
SELECT test_connection_interrupt_state_is_connection_local();
SELECT test_connection_frontend_protocol_is_connection_local();
SELECT test_connection_startup_state_is_connection_local();
SELECT test_client_connection_info_is_connection_local();
SELECT test_connection_security_state_is_connection_local();
PREPARE phase12_prepared_statement AS SELECT 42 AS answer;
SELECT name, statement, from_sql FROM pg_prepared_statements
	WHERE name = 'phase12_prepared_statement';
EXECUTE phase12_prepared_statement;
DEALLOCATE phase12_prepared_statement;
BEGIN;
CREATE TEMP TABLE phase12_on_commit_delete (answer int) ON COMMIT DELETE ROWS;
INSERT INTO phase12_on_commit_delete VALUES (42);
COMMIT;
SELECT count(*) AS remaining_rows FROM phase12_on_commit_delete;
DROP TABLE phase12_on_commit_delete;
BEGIN;
CREATE TEMP TABLE phase12_on_commit_drop (answer int) ON COMMIT DROP;
COMMIT;
SELECT to_regclass('pg_temp.phase12_on_commit_drop') IS NULL AS dropped;
CREATE TEMP SEQUENCE phase12_sequence_state;
SELECT nextval('phase12_sequence_state') AS first_nextval;
SELECT currval('phase12_sequence_state') AS current_value;
SELECT lastval() AS last_value;
DISCARD SEQUENCES;
SELECT nextval('phase12_sequence_state') AS nextval_after_discard;
SELECT currval('phase12_sequence_state') AS current_after_discard;
SELECT 1 + 2 AS operator_lookup_sum;
SELECT OPERATOR(pg_catalog.-) 5 AS operator_lookup_unary;
SELECT 3 OPERATOR(pg_catalog.*) 4 AS operator_lookup_product;
SELECT 'abc' ~ '^[[:alpha:]]+$' AS regex_alpha_cache;
SELECT '123' ~ '^[[:digit:]]+$' AS regex_digit_cache;
SELECT 'ABC' ~ '^[[:alpha:]]+$' AS regex_alpha_cache_reuse;
CREATE TEMP TABLE phase12_largeobject_state AS
	SELECT lo_from_bytea(0, 'phase12 large object'::bytea) AS loid;
SELECT encode(lo_get(loid), 'escape') AS lo_contents
	FROM phase12_largeobject_state;
SELECT lo_unlink(loid) = 1 AS lo_unlinked
	FROM phase12_largeobject_state;
DROP TABLE phase12_largeobject_state;
LISTEN phase12_async_state;
SELECT pg_listening_channels();
UNLISTEN *;
SELECT pg_listening_channels();
BEGIN;
SET LOCAL client_encoding TO SQL_ASCII;
SELECT current_setting('client_encoding') AS phase12_client_encoding;
COMMIT;
SELECT convert_from(
	convert_to('phase12 encoding state', current_setting('server_encoding')::name),
	current_setting('server_encoding')::name) AS phase12_encoding_roundtrip;
